import { localize, localizeHref } from "@/libs/locale";

const identity = {
  name: "Andy Morales",
  givenName: "Andy",
  title: "Human Architect",
};

const copy = {
  es: {
    line: "Arquitecto Humano · Atleta Híbrido",
    bio: "Diseño libros, herramientas y experiencias para el arte de vivir — una casa donde el alma pueda habitar el trabajo.",
    portrait: {
      alt: "Andy Morales corriendo una carrera de fondo",
    },
    cta: {
      label: "Escribir",
      href: "/#empieza-aqui",
    },
    story: {
      kicker: "Historia",
      opening: ["No llegué aquí estudiando arquitectura.", "Llegué reconstruyendo mi vida."],
      scripture: {
        reference: "Gálatas 2:20",
        note: "Literalmente me desintegré para luego renacer integrado.",
      },
      chapters: [
        "Comencé mi carrera en banca.",
        "Renuncié para reinventarme. Quebré.",
        "Salí de ella a los 27 construyendo una empresa de seis cifras.",
        "Volví a quebrar.",
        "Me volví a levantar. Esta vez reconstruyendo mi salud espiritual, emocional, mental, física, y financiera.",
      ],
      emphasis: "salud espiritual, emocional, mental, física, y financiera",
      closing: [
        "Fénix no nació de una teoría.",
        "Fénix nació de la reconstrucción.",
        "Hoy ayudo a diseñar la arquitectura devota humana para otras personas.",
      ],
      cta: {
        label: "Conoce mi trayectoria",
        destination: "LinkedIn",
      },
      folio: {
        kicker: "Láminas",
        label: "La reconstrucción",
        empty: "Fotografía en revelado",
        previous: "Anterior",
        next: "Siguiente",
        plates: [
          {
            id: "plate-01",
            numeral: "01",
            domain: "felicidad",
            subject: "El barrio",
            caption: "Comencé en un barrio popular de Colombia.",
            alt: "Andy Morales de niño con su familia en un hogar de barrio popular en Colombia.",
            image: "/images/story/1.jpg",
          },
          {
            id: "plate-02",
            numeral: "02",
            domain: "salud",
            subject: "El cuerpo antes",
            caption: "Era un flaco obeso con malos hábitos.",
            alt: "Andy Morales en su juventud, antes de reconstruir su salud.",
            image: "/images/story/2.jpg",
          },
          {
            id: "plate-03",
            numeral: "03",
            domain: "dinero",
            subject: "La tienda",
            caption: "Después de trabajar en una pequeña tienda.",
            alt: "Andy Morales en los años de trabajo en una pequeña tienda.",
            image: "/images/story/3.jpg",
          },
          {
            id: "plate-04",
            numeral: "04",
            domain: "dinero",
            subject: "Banca",
            caption: "Construí la típica idea de éxito, autos, viajes, titulos...",
            alt: "Andy Morales al comenzar su carrera en banca, junto a un viaje que representa la idea típica de éxito.",
            image: "/images/story/4.jpg",
          },
          {
            id: "plate-05",
            numeral: "05",
            domain: "felicidad",
            subject: "Reinventarme",
            caption: "Renuncié a una carrera en banca para reinventarme.",
            alt: "Andy Morales en un estadio, en los años de reinventarse.",
            image: "/images/story/5.jpg",
          },
          {
            id: "plate-06",
            numeral: "06",
            domain: "felicidad",
            subject: "El quiebre",
            caption: "Regresé a mi país a construir empresa pero caí en depresión y quiebra 2 veces.",
            alt: "Una figura recorriendo un camino solitario, en los años de quiebra y depresión.",
            image: "/images/story/6.jpg",
          },
          {
            id: "plate-07",
            numeral: "07",
            domain: "salud",
            subject: "El renacimiento",
            caption: "En 2017 construí una empresa de 6 cifras USD y así comenzó mi proceso de renacimiento.",
            alt: "Una mano sobre la Biblia, al comienzo del proceso de renacimiento.",
            image: "/images/story/7.jpg",
          },
          {
            id: "plate-08",
            numeral: "08",
            domain: "salud",
            subject: "El cuerpo después",
            caption: "Hoy ayudo a otras personas a elevar sus obras de vida.",
            alt: "Andy Morales corriendo, entrenando, nadando y con su familia.",
            image: "/images/story/8.jpg",
          },
          {
            id: "plate-09",
            numeral: "09",
            subject: "Las tres arquitecturas",
            caption: "",
            alt: "Tres fotografías de Andy Morales: el cuerpo, la paz interior y la familia.",
            image: "/images/story/9.jpg",
            bands: [
              { title: "Arquitectura del Cuerpo", line: "Body Architecture" },
              { title: "Arquitectura Happeace", line: "Happeace Architecture" },
              { title: "Arquitectura del dinero", line: "Money Architecture" },
            ],
          },
        ],
      },
    },
  },
  en: {
    line: "Human Architect · Hybrid Athlete",
    bio: "I design books, tools, and experiences for the art of living — a house where the soul can inhabit the work.",
    portrait: {
      alt: "Andy Morales running a long-distance race",
    },
    cta: {
      label: "Write",
      href: "/#empieza-aqui",
    },
    story: {
      kicker: "Story",
      opening: ["I did not arrive here by studying architecture.", "I arrived by rebuilding my life."],
      scripture: {
        reference: "Galatians 2:20",
        note: "I quite literally came apart — then was born again, integrated.",
      },
      chapters: [
        "I began my career in banking.",
        "I resigned in order to reinvent myself. I went bankrupt.",
        "I came out of it at 27 building a six-figure company.",
        "I went bankrupt again.",
        "I rose again. This time by rebuilding my spiritual, emotional, mental, physical, and financial health.",
      ],
      emphasis: "spiritual, emotional, mental, physical, and financial health",
      closing: [
        "Fénix was not born of a theory.",
        "Fénix was born of reconstruction.",
        "Today I help other people design a devoted human architecture.",
      ],
      cta: {
        label: "See my trajectory",
        destination: "LinkedIn",
      },
      folio: {
        kicker: "Plates",
        label: "The reconstruction",
        empty: "Photograph in development",
        previous: "Previous",
        next: "Next",
        plates: [
          {
            id: "plate-01",
            numeral: "01",
            domain: "felicidad",
            subject: "The neighborhood",
            caption: "I began in a working-class neighborhood in Colombia.",
            alt: "Andy Morales as a child with his family in a working-class home in Colombia.",
            image: "/images/story/1.jpg",
          },
          {
            id: "plate-02",
            numeral: "02",
            domain: "salud",
            subject: "The body before",
            caption: "I was a skinny obese man with poor habits.",
            alt: "Andy Morales in his youth, before rebuilding his health.",
            image: "/images/story/2.jpg",
          },
          {
            id: "plate-03",
            numeral: "03",
            domain: "dinero",
            subject: "The shop",
            caption: "After working in a small shop.",
            alt: "Andy Morales in the years of working in a small shop.",
            image: "/images/story/3.jpg",
          },
          {
            id: "plate-04",
            numeral: "04",
            domain: "dinero",
            subject: "Banking",
            caption: "I built the typical idea of success: cars, travel, titles...",
            alt: "Andy Morales at the beginning of his banking career, beside a journey that represents the typical idea of success.",
            image: "/images/story/4.jpg",
          },
          {
            id: "plate-05",
            numeral: "05",
            domain: "felicidad",
            subject: "Reinvention",
            caption: "I left a career in banking in order to reinvent myself.",
            alt: "Andy Morales in a stadium, in the years of reinventing himself.",
            image: "/images/story/5.jpg",
          },
          {
            id: "plate-06",
            numeral: "06",
            domain: "felicidad",
            subject: "The breaking",
            caption: "I returned to my country to build a company, but fell into depression and bankruptcy twice.",
            alt: "A figure walking a solitary path, in the years of bankruptcy and depression.",
            image: "/images/story/6.jpg",
          },
          {
            id: "plate-07",
            numeral: "07",
            domain: "salud",
            subject: "Rebirth",
            caption: "In 2017 I built a six-figure USD company, and so began my process of rebirth.",
            alt: "A hand on the Bible, at the beginning of the process of rebirth.",
            image: "/images/story/7.jpg",
          },
          {
            id: "plate-08",
            numeral: "08",
            domain: "salud",
            subject: "The body after",
            caption: "Today I help other people raise the work of their lives.",
            alt: "Andy Morales running, training, swimming, and with his family.",
            image: "/images/story/8.jpg",
          },
          {
            id: "plate-09",
            numeral: "09",
            subject: "The three architectures",
            caption: "",
            alt: "Three photographs of Andy Morales: the body, inner peace, and family.",
            image: "/images/story/9.jpg",
            bands: [
              { title: "Body Architecture", line: "Body Architecture" },
              { title: "Happeace Architecture", line: "Happeace Architecture" },
              { title: "Money Architecture", line: "Money Architecture" },
            ],
          },
        ],
      },
    },
  },
};

export function getFounder(locale) {
  const localized = localize(copy, locale);
  return {
    ...identity,
    ...localized,
    cta: {
      ...localized.cta,
      href: localizeHref(localized.cta.href, locale),
    },
  };
}
