// Founder entity — canonical data for The Story, House profile, and Person schema.
export const founder = {
  name: "Andy Morales",
  givenName: "Andy",
  title: "Human Architect",
  line: "Arquitecto Humano · Atleta Híbrido",
  bio: "Diseño libros, herramientas y experiencias para el arte de vivir — una casa donde el alma pueda habitar el trabajo.",
  portrait: {
    alt: "Andy Morales corriendo una carrera de fondo",
  },
  cta: {
    label: "Escribir",
    href: "/#empieza-aqui",
  },
  story: {
    opening: ["No llegué aquí estudiando arquitectura.", "Llegué reconstruyendo mi vida."],
    scripture: {
      reference: "Gálatas 2:20",
      note: "Literalmente me desintegré para luego renacer integrado.",
    },
    chapters: [
      "Comencé mi carrera en banca.",
      "Renuncié para reinventarme. Quebré.",
      "Salí de ella a los 27 construyendo una empresa de seis cifras.",
      "Volví a quebrar.",
      "Me volví a levantar. Esta vez reconstruyendo mi salud espiritual, emocional, mental, física, y financiera.",
    ],
    emphasis: "salud espiritual, emocional, mental, física, y financiera",
    closing: [
      "Fénix no nació de una teoría.",
      "Fénix nació de la reconstrucción.",
      "Hoy ayudo a diseñar la arquitectura devota humana para otras personas.",
    ],
    cta: {
      label: "Conoce mi trayectoria",
      destination: "LinkedIn",
    },
    folio: {
      kicker: "Láminas",
      label: "La reconstrucción",
      empty: "Fotografía en revelado",
      previous: "Lámina anterior",
      next: "Lámina siguiente",
      plates: [
        {
          id: "plate-01",
          numeral: "01",
          domain: "felicidad",
          subject: "El barrio",
          caption: "Comencé en un barrio popular de Colombia",
          alt: "Andy Morales de niño con su familia en un hogar de barrio popular en Colombia.",
          image: "/images/story/1.jpg",
        },
        {
          id: "plate-02",
          numeral: "02",
          domain: "salud",
          subject: "El cuerpo antes",
          caption: "Era un flaco obeso con malos hábitos.",
          alt: "Andy Morales en su juventud, antes de reconstruir su salud.",
                    image: "/images/story/2.jpg",
        },
        {
          id: "plate-03",
          numeral: "03",
          domain: "dinero",
          subject: "La tienda",
          caption: "Después de trabajar en una pequeña tienda",
          alt: "Andy Morales en los años de trabajo en una pequeña tienda.",
          image: "/images/story/3.jpg",
        },
        {
          id: "plate-04",
          numeral: "04",
          domain: "dinero",
          subject: "Banca",
          caption: "Construí la típica idea de éxito, autos, viajes, titulos...",
          alt: "Andy Morales al comenzar su carrera en banca, junto a un viaje que representa la idea típica de éxito.",
          image: "/images/story/4.jpg",
        },
        {
          id: "plate-05",
          numeral: "05",
          domain: "felicidad",
          subject: "Reinventarme",
          caption: "Renuncié a una carrera en banca para reinventarme ",
          alt: "Andy Morales en un estadio, en los años de reinventarse.",
          image: "/images/story/5.jpg",
        },
        {
          id: "plate-06",
          numeral: "06",
          domain: "felicidad",
          subject: "El quiebre",
          caption: "Regresé a mi país a construir empresa pero caí en depresión y quiebra 2 veces",
          alt: "Una figura recorriendo un camino solitario, en los años de quiebra y depresión.",
          image: "/images/story/6.jpg",
        },
        {
          id: "plate-07",
          numeral: "07",
          domain: "salud",
          subject: "El renacimiento",
          caption: "Construí una empresa de 6 cifras y así comenzó mi proceso de renacimiento",
          alt: "Una mano sobre la Biblia, al comienzo del proceso de renacimiento.",
          image: "/images/story/7.jpg",
        },
        {
          id: "plate-08",
          numeral: "08",
          domain: "salud",
          subject: "El cuerpo después",
          caption: "Hoy ayudo a otras personas a elevar sus obras de vida.",
          alt: "Andy Morales corriendo, entrenando, nadando y con su familia.",
          image: "/images/story/8.jpg",
        },
        {
          id: "plate-09",
          numeral: "09",
          subject: "Las tres arquitecturas",
          caption: "",
          alt: "Tres fotografías de Andy Morales: el cuerpo, la paz interior y la familia.",
          image: "/images/story/9.jpg",
          bands: [
            { title: "Arquitectura del Cuerpo", line: "Body Architecture" },
            { title: "Arquitectura Happeace", line: "Happeace Architecture" },
            { title: "Arquitectura del dinero", line: "Money Architecture" },
          ],
        },
      ],
    },
  },
};
